TOPIC_KEYWORDS = {
    "Drug Discovery & Cheminformatics": [
        "drug discovery",
        "small-molecule discovery",
        "computer-aided drug design",
        "cadd",
        "cheminformatics",
        "virtual screening",
        "high-throughput virtual screening",
        "structure-based drug design",
        "ligand-based drug design",
        "molecular docking",
        "protein-ligand",
        "binding affinity",
        "binding pose",
        "hit identification",
        "hit finding",
        "hit-to-lead",
        "lead optimization",
        "fragment-based drug design",
        "fragment screening",
        "pharmacophore",
        "scaffold hopping",
        "dna-encoded library",
        "polypharmacology",
        "selectivity prediction",
    ],
    "Generative Chemistry & Molecular Design": [
        "generative chemistry",
        "molecular generation",
        "de novo molecular design",
        "de novo design",
        "molecule generation",
        "molecule optimization",
        "molecular optimization",
        "molecular design",
        "inverse design",
        "generative model",
        "diffusion model for molecules",
        "diffusion model",
        "flow matching",
        "smiles generation",
        "reaction generation",
        "library design",
        "compound design",
        "multi-objective optimization",
    ],
    "Computational Chemistry": [
        "computational chemistry",
        "quantum chemistry",
        "density functional theory",
        "dft",
        "molecular dynamics",
        "enhanced sampling",
        "metadynamics",
        "umbrella sampling",
        "free energy",
        "free energy perturbation",
        "relative binding free energy",
        "absolute binding free energy",
        "thermodynamic integration",
        "mm/pbsa",
        "fep",
        "force field",
        "ab initio",
        "electronic structure",
        "qm/mm",
        "protein-ligand simulation",
        "alchemical free energy",
    ],
    "QSAR & ADMET": [
        "qsar",
        "qspr",
        "admet",
        "dmpk",
        "molecular property prediction",
        "property prediction",
        "bioactivity prediction",
        "potency prediction",
        "drug-likeness",
        "solubility",
        "permeability",
        "bbb permeability",
        "blood-brain barrier",
        "clearance",
        "microsomal stability",
        "cyp",
        "cyp450",
        "herg",
        "bioavailability",
        "toxicity prediction",
        "pharmacokinetic prediction",
    ],
    "Uncertainty Quantification": [
        "uncertainty quantification",
        "uncertainty estimation",
        "predictive uncertainty",
        "uncertainty-aware",
        "calibration",
        "confidence calibration",
        "confidence estimation",
        "conformal prediction",
        "epistemic uncertainty",
        "aleatoric uncertainty",
        "probabilistic prediction",
        "out-of-distribution",
        "ood",
        "distribution shift",
        "applicability domain",
        "reliability estimation",
        "error estimation",
    ],
    "Bayesian Optimization & Active Learning": [
        "bayesian optimization",
        "active learning",
        "closed-loop",
        "autonomous discovery",
        "adaptive sampling",
        "acquisition function",
        "sequential design",
        "experiment selection",
        "batch active learning",
        "multi-fidelity optimization",
        "uncertainty sampling",
        "expected improvement",
        "thompson sampling",
        "bayesian experimental design",
        "design-make-test",
    ],
    "Molecular Representation Learning": [
        "molecular representation",
        "representation learning",
        "molecular embedding",
        "molecular fingerprint",
        "graph neural network",
        "graph transformer",
        "message passing neural network",
        "molecular graph",
        "graph representation learning",
        "equivariant graph neural network",
        "geometric deep learning",
        "self-supervised",
        "contrastive learning",
        "molecular language model",
        "chemical language model",
        "smiles language model",
        "smiles encoder",
        "foundation model for molecules",
        "molecular foundation model",
        "pretrained molecular model",
        "graph pretraining",
        "protein-ligand model",
        "3d molecular representation",
    ],
}

TOPIC_TITLE_WEIGHTS = {
    "Drug Discovery & Cheminformatics": 2,
    "Generative Chemistry & Molecular Design": 3,
    "Computational Chemistry": 2,
    "QSAR & ADMET": 2,
    "Uncertainty Quantification": 3,
    "Bayesian Optimization & Active Learning": 3,
    "Molecular Representation Learning": 3,
}

TOPIC_ABSTRACT_WEIGHTS = {
    "Drug Discovery & Cheminformatics": 1,
    "Generative Chemistry & Molecular Design": 2,
    "Computational Chemistry": 1,
    "QSAR & ADMET": 1,
    "Uncertainty Quantification": 2,
    "Bayesian Optimization & Active Learning": 2,
    "Molecular Representation Learning": 2,
}

FETCH_KEYWORDS = [
    "drug discovery",
    "computer-aided drug design",
    "cheminformatics",
    "virtual screening",
    "structure-based drug design",
    "ligand-based drug design",
    "molecular docking",
    "protein-ligand",
    "binding affinity",
    "lead optimization",
    "fragment-based drug design",
    "pharmacophore",
    "scaffold hopping",
    "qsar",
    "qspr",
    "admet",
    "dmpk",
    "bioactivity prediction",
    "molecular property prediction",
    "free energy perturbation",
    "molecular dynamics",
    "generative chemistry",
    "molecular generation",
    "de novo molecular design",
    "molecule optimization",
    "molecular design",
    "applicability domain",
    "molecular representation",
    "molecular machine learning",
    "molecular language model",
    "chemical language model",
    "foundation model for molecules",
]

METHOD_KEYWORDS = [
    "active learning",
    "bayesian optimization",
    "uncertainty quantification",
    "uncertainty estimation",
    "conformal prediction",
    "calibration",
    "applicability domain",
    "out-of-distribution",
    "representation learning",
    "graph neural network",
    "graph transformer",
    "molecular language model",
    "chemical language model",
    "foundation model",
    "self-supervised",
    "contrastive learning",
    "diffusion model",
    "generative model",
]

MOLECULAR_CONTEXT_TERMS = [
    "drug",
    "molecule",
    "molecular",
    "chemical",
    "chemistry",
    "compound",
    "small molecule",
    "ligand",
    "protein-ligand",
    "binding affinity",
    "virtual screening",
    "docking",
    "bioactivity",
    "medicinal chemistry",
    "admet",
    "qsar",
    "molecular property",
]

COMPUTATIONAL_CONTEXT_TERMS = [
    "drug discovery",
    "computer-aided drug design",
    "cadd",
    "cheminformatics",
    "virtual screening",
    "structure-based drug design",
    "binding affinity",
    "protein-ligand",
    "computational",
    "in silico",
    "molecular dynamics",
    "free energy",
    "fep",
    "qsar",
    "admet",
    "representation learning",
    "graph neural network",
    "graph transformer",
    "molecular machine learning",
    "generative chemistry",
    "molecular generation",
    "bayesian optimization",
    "active learning",
    "uncertainty",
    "conformal prediction",
]

COARSE_CHEMISTRY_TERMS = [
    "chemistry",
    "molecule",
    "molecular",
    "ligand",
    "compound",
    "screening",
    "reaction",
    "drug",
    "protein",
    "binding",
]

FIELD_KEYWORDS = {
    "drug discovery": 5,
    "small-molecule discovery": 4,
    "computer-aided drug design": 5,
    "cadd": 4,
    "cheminformatics": 6,
    "virtual screening": 5,
    "structure-based drug design": 5,
    "ligand-based drug design": 4,
    "molecular docking": 4,
    "protein-ligand": 4,
    "binding affinity": 5,
    "hit-to-lead": 4,
    "lead optimization": 4,
    "fragment-based drug design": 4,
    "pharmacophore": 3,
    "scaffold hopping": 4,
    "generative chemistry": 6,
    "molecular generation": 6,
    "de novo molecular design": 6,
    "molecule optimization": 5,
    "molecular design": 4,
    "diffusion model": 2,
    "generative model": 2,
    "computational chemistry": 4,
    "quantum chemistry": 3,
    "molecular dynamics": 3,
    "free energy": 3,
    "free energy perturbation": 5,
    "relative binding free energy": 5,
    "absolute binding free energy": 5,
    "thermodynamic integration": 4,
    "qm/mm": 3,
    "fep": 5,
    "qsar": 5,
    "qspr": 4,
    "admet": 5,
    "dmpk": 4,
    "property prediction": 4,
    "molecular property prediction": 5,
    "bioactivity prediction": 5,
    "drug-likeness": 3,
    "solubility": 2,
    "permeability": 2,
    "clearance": 2,
    "microsomal stability": 3,
    "cyp": 2,
    "cyp450": 3,
    "herg": 3,
    "blood-brain barrier": 3,
    "bbb permeability": 3,
    "uncertainty quantification": 6,
    "uncertainty estimation": 5,
    "uncertainty-aware": 5,
    "conformal prediction": 6,
    "calibration": 4,
    "confidence estimation": 4,
    "predictive uncertainty": 5,
    "out-of-distribution": 4,
    "distribution shift": 4,
    "applicability domain": 5,
    "bayesian optimization": 6,
    "active learning": 6,
    "closed-loop": 4,
    "acquisition function": 4,
    "multi-fidelity optimization": 4,
    "molecular representation": 6,
    "representation learning": 5,
    "graph neural network": 5,
    "graph transformer": 5,
    "message passing neural network": 5,
    "equivariant graph neural network": 5,
    "molecular embedding": 5,
    "molecular fingerprint": 3,
    "molecular machine learning": 6,
    "molecular language model": 6,
    "chemical language model": 6,
    "foundation model for molecules": 6,
    "molecular foundation model": 6,
    "pretrained molecular model": 5,
    "self-supervised": 4,
    "contrastive learning": 4,
    "smiles encoder": 4,
    "protein-ligand model": 5,
}

NEGATIVE_KEYWORDS = {
    "polymer": 4,
    "polymers": 4,
    "battery": 6,
    "supercapacitor": 6,
    "electrocatalysis": 6,
    "catalyst": 4,
    "catalysis": 4,
    "surface analysis": 4,
    "surface reconstruction": 4,
    "xps": 6,
    "spectra": 3,
    "spectroscopy": 4,
    "interatomic potential": 4,
    "defect": 4,
    "strong coupling": 4,
    "photonic": 4,
    "photovoltaic": 5,
    "perovskite": 5,
    "alloy": 5,
    "semiconductor": 5,
    "materials": 4,
    "gas-phase": 3,
    "corrosion": 4,
    "combustion": 4,
    "membrane separation": 4,
}

GENERIC_BIOMEDICAL_TERMS = [
    "bioinformatics analysis",
    "network pharmacology",
    "single-cell",
    "single cell",
    "transcriptome",
    "transcriptomics",
    "gene expression",
    "immune infiltration",
    "immune microenvironment",
    "mendelian randomization",
    "prognostic",
    "prognosis",
    "biomarker",
    "gut microbiota",
    "survival analysis",
    "weighted gene co-expression",
    "differentially expressed genes",
    "rna-seq",
    "mrna expression",
]

AI_CORE_TITLE_TERMS = [
    "active learning",
    "bayesian optimization",
    "uncertainty quantification",
    "uncertainty estimation",
    "conformal prediction",
    "applicability domain",
    "molecular representation",
    "representation learning",
    "molecular machine learning",
    "graph neural network",
    "graph transformer",
    "molecular embedding",
    "molecular language model",
    "chemical language model",
    "foundation model for molecules",
    "molecular foundation model",
    "self-supervised",
    "generative chemistry",
    "de novo molecular design",
]

PAPER_SCORING_KEYWORDS = [
    "drug discovery",
    "cheminformatics",
    "binding affinity",
    "protein-ligand",
    "lead optimization",
    "generative chemistry",
    "molecular generation",
    "de novo molecular design",
    "qsar",
    "admet",
    "active learning",
    "bayesian optimization",
    "uncertainty quantification",
    "conformal prediction",
    "calibration",
    "molecular representation",
    "representation learning",
    "molecular machine learning",
    "graph neural network",
    "graph transformer",
    "molecular embedding",
    "molecular language model",
    "chemical language model",
    "fep",
    "free energy perturbation",
]

PAPER_SCORING_NOVELTY = [
    "foundation model",
    "molecular foundation model",
    "diffusion",
    "multimodal",
    "self-supervised",
    "benchmark",
    "state-of-the-art",
]

PUBMED_DIRECT_TERMS = [
    "drug discovery",
    "computer-aided drug design",
    "cheminformatics",
    "virtual screening",
    "molecular docking",
    "binding affinity",
    "protein-ligand",
    "lead optimization",
    "fragment-based drug design",
    "qsar",
    "admet",
    "dmpk",
    "free energy perturbation",
    "molecular dynamics",
    "generative chemistry",
    "de novo molecular design",
    "molecular generation",
    "molecular design",
    "molecular representation learning",
    "molecular machine learning",
]

PUBMED_METHOD_TERMS = [
    "active learning",
    "bayesian optimization",
    "uncertainty quantification",
    "uncertainty estimation",
    "conformal prediction",
    "calibration",
    "applicability domain",
    "graph neural network",
    "graph transformer",
    "molecular language model",
    "chemical language model",
    "foundation model",
    "self-supervised",
    "contrastive learning",
    "diffusion model",
    "generative model",
]

ARXIV_CATEGORIES = [
    "cat:q-bio.QM",
    "cat:cs.LG",
    "cat:stat.ML",
    "cat:physics.chem-ph",
]

ARXIV_DIRECT_TERMS = [
    "drug discovery",
    "cheminformatics",
    "virtual screening",
    "molecular docking",
    "binding affinity",
    "protein-ligand",
    "qsar",
    "admet",
    "molecular generation",
    "de novo molecular design",
    "molecular design",
    "molecular dynamics",
    "free energy perturbation",
    "molecular machine learning",
    "molecular language model",
    "foundation model for molecules",
]

ARXIV_METHOD_TERMS = [
    "active learning",
    "bayesian optimization",
    "conformal prediction",
    "uncertainty quantification",
    "graph neural network",
    "graph transformer",
    "foundation model",
]

ARXIV_CONTEXT_TERMS = [
    "molecular",
    "molecule",
    "drug",
    "ligand",
    "protein-ligand",
    "chemical",
    "chemistry",
    "compound",
]


def flatten_topic_keywords():
    keywords = []
    for topic_keywords in TOPIC_KEYWORDS.values():
        keywords.extend(topic_keywords)
    return keywords


def keyword_match(text):
    lowered = (text or "").lower()
    direct_hit = any(keyword in lowered for keyword in FETCH_KEYWORDS)
    contextual_hit = (
        any(keyword in lowered for keyword in METHOD_KEYWORDS)
        and any(term in lowered for term in MOLECULAR_CONTEXT_TERMS)
    )
    return direct_hit or contextual_hit


def build_interest_text():
    return ", ".join(flatten_topic_keywords())


def _pubmed_field_clause(term):
    return f"\"{term}\"[Title/Abstract]"


def build_pubmed_query():
    direct_block = " OR ".join(_pubmed_field_clause(term) for term in PUBMED_DIRECT_TERMS)
    method_block = " OR ".join(_pubmed_field_clause(term) for term in PUBMED_METHOD_TERMS)
    context_block = " OR ".join(_pubmed_field_clause(term) for term in MOLECULAR_CONTEXT_TERMS)

    return f"""
(
  ({direct_block})
  OR
  (({method_block}) AND ({context_block}))
)
"""


def _arxiv_clause(term):
    if " " in term or "-" in term:
        return f'all:"{term}"'
    return f"all:{term}"


def build_arxiv_query():
    category_block = " OR ".join(ARXIV_CATEGORIES)
    direct_block = " OR ".join(_arxiv_clause(term) for term in ARXIV_DIRECT_TERMS)
    method_block = " OR ".join(_arxiv_clause(term) for term in ARXIV_METHOD_TERMS)
    context_block = " OR ".join(_arxiv_clause(term) for term in ARXIV_CONTEXT_TERMS)
    return f"(({category_block}) AND (({direct_block}) OR (({method_block}) AND ({context_block}))))"
